#Requires -Version 5.1
# Creates secrets/supabase-selfhost-mcp.env from POSTGRES_PASSWORD on YC db-01 (password not printed).
# Tunnel: OpenSSH -L via ssh.exe (AdGuard exclusion) → local 15433 → VM :5433.
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Out = Join-Path $Root "secrets\supabase-selfhost-mcp.env"

$SshHost = if ($env:SFRFR_SUPABASE_SSH_HOST) { $env:SFRFR_SUPABASE_SSH_HOST } else { "51.250.69.237" }
$SshUser = if ($env:SFRFR_SUPABASE_SSH_USER) { $env:SFRFR_SUPABASE_SSH_USER } else { "sfrfr" }
$SshTarget = "${SshUser}@${SshHost}"

$sshKey = Join-Path $env:USERPROFILE ".ssh\id_ed25519"
if (-not (Test-Path $sshKey)) {
  $alt = Join-Path $env:USERPROFILE ".ssh\id_rsa"
  if (Test-Path $alt) { $sshKey = $alt }
}

Write-Host "Reading POSTGRES_PASSWORD from $SshTarget ..."

$remote = @'
from pathlib import Path
p = Path("/opt/sfrfr-supabase/supabase/docker/.env")
vals = {}
for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, v = line.split("=", 1)
    vals[k.strip()] = v.strip().strip('"').strip("'")
pwd = vals.get("POSTGRES_PASSWORD") or vals.get("POSTGRES_PASSWORD_ENC") or ""
user = vals.get("POSTGRES_USER") or "postgres"
db = vals.get("POSTGRES_DB") or "postgres"
print("|".join([user, db, pwd]))
'@

$sshArgs = @(
  "-i", $sshKey,
  "-o", "IdentitiesOnly=yes",
  "-o", "BatchMode=yes",
  "-o", "ConnectTimeout=15",
  $SshTarget,
  "cat > /tmp/sfrfr_mcp_boot.py && python3 /tmp/sfrfr_mcp_boot.py && rm -f /tmp/sfrfr_mcp_boot.py"
)
$line = $remote | & "$env:SystemRoot\System32\OpenSSH\ssh.exe" @sshArgs
if (-not $line) { throw "Empty SSH response for $SshTarget" }

$parts = ($line | Select-Object -Last 1).ToString().Trim() -split "\|", 3
if ($parts.Count -lt 3 -or -not $parts[2]) {
  throw "Cannot parse .env (expected user|db|password)"
}
$user = $parts[0]
$db = $parts[1]
$password = $parts[2]

function Encode-EnvValue([string]$v) {
  if ($v -match '[\s#"\\]') {
    return '"' + ($v -replace '\\', '\\' -replace '"', '\"') + '"'
  }
  return $v
}

$Content = @"
# Generated by bootstrap_supabase_selfhost_mcp.ps1 - do not commit
DB_TYPE=postgres
DB_USER=$user
DB_PASSWORD=$(Encode-EnvValue $password)
DB_NAME=$db
SSH_HOST=$SshHost
SSH_USER=$SshUser
SSH_KEY=$sshKey
SSH_LOCAL_PORT=15433
SSH_REMOTE_PORT=5433
"@

New-Item -ItemType Directory -Force -Path (Split-Path $Out) | Out-Null
Set-Content -Path $Out -Value $Content -Encoding UTF8
Write-Host "OK -> $Out"
Write-Host "DB_USER=$user DB_NAME=$db (password hidden)"
Write-Host "OpenSSH tunnel target: ${SshUser}@${SshHost} -L 15433:127.0.0.1:5433"
Write-Host "Next: Cursor Settings -> MCP -> Reload (supabase-selfhost)."
Write-Host "AdGuard: exclude C:\Windows\System32\OpenSSH\ssh.exe"
