#Requires -Version 5.1
# Creates secrets/supabase-selfhost-mcp.env from VPS DATABASE_URL (password not printed).
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Out = Join-Path $Root "secrets\supabase-selfhost-mcp.env"
$Vps = if ($env:SFRFR_VPS_SSH) { $env:SFRFR_VPS_SSH } else { "root@91.229.11.147" }

Write-Host "Reading DATABASE_URL from $Vps ..."

$remote = @'
import re, urllib.parse
from pathlib import Path
env = Path("/opt/sfrfr/.env").read_text(encoding="utf-8", errors="replace")
vals = {}
for line in env.splitlines():
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, v = line.split("=", 1)
    vals[k.strip()] = v.strip().strip('"').strip("'")
u = re.sub(r"^postgresql\+[^=:]+", "postgresql", vals.get("DATABASE_URL", ""))
p = urllib.parse.urlparse(u)
pwd = urllib.parse.unquote(p.password or "")
print("|".join([
    p.hostname or "",
    str(p.port or 5433),
    p.username or "postgres",
    (p.path or "/postgres").lstrip("/") or "postgres",
    pwd,
]))
'@

$line = $remote | ssh -o BatchMode=yes -o ConnectTimeout=15 $Vps "cat > /tmp/sfrfr_mcp_boot.py && python3 /tmp/sfrfr_mcp_boot.py && rm -f /tmp/sfrfr_mcp_boot.py"
if (-not $line) { throw "Empty SSH response for $Vps" }

$parts = $line -split "\|", 5
if ($parts.Count -lt 5 -or -not $parts[4]) {
  throw "Cannot parse DATABASE_URL (expected host|port|user|db|password)"
}
$hostName = $parts[0]
$port = $parts[1]
$user = $parts[2]
$db = $parts[3]
$password = $parts[4]

function Encode-EnvValue([string]$v) {
  if ($v -match '[\s#"\\]') {
    return '"' + ($v -replace '\\', '\\' -replace '"', '\"') + '"'
  }
  return $v
}

$jumpHost = if ($Vps -match "@(.+)$") { $Matches[1] } else { "91.229.11.147" }
$jumpUser = if ($Vps -match "^([^@]+)@") { $Matches[1] } else { "root" }
$sshKey = Join-Path $env:USERPROFILE ".ssh\id_ed25519"
if (-not (Test-Path $sshKey)) {
  $alt = Join-Path $env:USERPROFILE ".ssh\id_rsa"
  if (Test-Path $alt) { $sshKey = $alt }
}

$Content = @"
# Generated by bootstrap_supabase_selfhost_mcp.ps1 - do not commit
DB_TYPE=postgres
DB_HOST=$hostName
DB_PORT=$port
DB_USER=$user
DB_PASSWORD=$(Encode-EnvValue $password)
DB_NAME=$db
SSH_HOST=$jumpHost
SSH_USER=$jumpUser
SSH_KEY=$sshKey
"@

New-Item -ItemType Directory -Force -Path (Split-Path $Out) | Out-Null
Set-Content -Path $Out -Value $Content -Encoding UTF8
Write-Host "OK -> $Out"
Write-Host "DB_HOST=$hostName DB_PORT=$port DB_USER=$user DB_NAME=$db (password hidden)"
Write-Host "SSH jump: ${jumpUser}@${jumpHost}"
Write-Host "Next: Cursor Settings -> MCP -> Reload (supabase-selfhost)."
Write-Host "If connect fails: ensure VM C listens on :5433 (docs/ops/supabase-selfhost-mcp.md)."
