#!/usr/bin/env bash
# Применить короткую главную + CSS + статьи 01–09 на VPS WordPress.
# Запуск на сервере: bash /opt/sfrfr/scripts/wp_apply_landing_vps.sh
set -euo pipefail
SITE_DIR="${SITE_DIR:-/var/www/taxi-doroga-dobra}"
APP_DIR="${APP_DIR:-/opt/sfrfr}"
WP=(wp --allow-root --path="$SITE_DIR")

export SFRFR_HOME_PATH="${APP_DIR}/scripts/assets/sfrfr-home.html"
export SFRFR_CSS_PATH="${APP_DIR}/scripts/assets/sfrfr-landing.css"
export SFRFR_BLOG_ASSETS="${APP_DIR}/scripts/assets/blog"

if [ -f "${APP_DIR}/.env" ]; then
  MAX_CHAT_URL="$(grep -m1 '^MAX_CHAT_URL=' "${APP_DIR}/.env" | cut -d= -f2- | tr -d '"\r' || true)"
  MAX_PUBLIC_BOT_URL="$(grep -m1 '^MAX_PUBLIC_BOT_URL=' "${APP_DIR}/.env" | cut -d= -f2- | tr -d '"\r' || true)"
  MAX_CHANNEL_URL="$(grep -m1 '^MAX_CHANNEL_URL=' "${APP_DIR}/.env" | cut -d= -f2- | tr -d '"\r' || true)"
  export MAX_CHAT_URL MAX_PUBLIC_BOT_URL MAX_CHANNEL_URL
fi

cd "$APP_DIR"
git log -1 --oneline
test -f scripts/assets/sfrfr-home.html
test -f scripts/assets/blog/09-faq-rasshirennyy.html

"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_apply_landing_css.php"
echo
"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_apply_author_display.php"
echo
if [[ -f "${APP_DIR}/scripts/wp_ensure_bvi.sh" ]]; then
  bash "${APP_DIR}/scripts/wp_ensure_bvi.sh" || echo "WARN: wp_ensure_bvi.sh failed"
fi
"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_apply_home.php"
echo
if [[ -f "${APP_DIR}/scripts/wp_ensure_sitelink_titles.php" ]]; then
  "${WP[@]}" eval-file "${APP_DIR}/scripts/wp_ensure_sitelink_titles.php" || echo "WARN: sitelink titles failed"
  echo
fi
"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_upsert_legal_pages.php"
echo
"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_set_public_email.php"
echo
"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_hide_astra_copyright.php"
echo
# MU: скрытие копирайта Astra (на случай если CSS Customizer проигрывает)
cp -f "${APP_DIR}/scripts/wp-mu-plugins/sfrfr-hide-astra-copyright.php" \
  "${SITE_DIR}/wp-content/mu-plugins/sfrfr-hide-astra-copyright.php"
echo "MU hide-copyright OK"
cp -f "${APP_DIR}/scripts/wp-mu-plugins/sfrfr-site-footer.php" \
  "${SITE_DIR}/wp-content/mu-plugins/sfrfr-site-footer.php"
cp -f "${APP_DIR}/scripts/wp-mu-plugins/sfrfr-site-search.php" \
  "${SITE_DIR}/wp-content/mu-plugins/sfrfr-site-search.php"
# Copy awards gallery into WP uploads on landing apply too
AWARDS_SRC="${APP_DIR}/scripts/assets/awards"
AWARDS_DST="${SITE_DIR}/wp-content/uploads/sfrfr/awards"
mkdir -p "${AWARDS_DST}"
if compgen -G "${AWARDS_SRC}/award-*.jpg" > /dev/null; then
  rm -f "${AWARDS_DST}/"award-*.jpg 2>/dev/null || true
  cp -f "${AWARDS_SRC}/award-"*.jpg "${AWARDS_DST}/"
  chown -R www-data:www-data "${SITE_DIR}/wp-content/uploads/sfrfr" 2>/dev/null || true
fi
cp -f "${APP_DIR}/scripts/assets/sfrfr-awards.js" \
  "${SITE_DIR}/wp-content/mu-plugins/sfrfr-awards.js"
cp -f "${APP_DIR}/scripts/wp-mu-plugins/sfrfr-yandex-verification.php" \
  "${SITE_DIR}/wp-content/mu-plugins/sfrfr-yandex-verification.php"
cp -f "${APP_DIR}/scripts/wp-mu-plugins/sfrfr-recaptcha-lead.php" \
  "${SITE_DIR}/wp-content/mu-plugins/sfrfr-recaptcha-lead.php"
cp -f "${APP_DIR}/scripts/assets/sfrfr-recaptcha-lead.js" \
  "${SITE_DIR}/wp-content/mu-plugins/sfrfr-recaptcha-lead.js" 2>/dev/null || true
# Публичный конфиг лида/капчи: www-data не читает /opt/sfrfr/.env
env_get() {
  local k="$1"
  grep -m1 "^${k}=" "${APP_DIR}/.env" 2>/dev/null | cut -d= -f2- | tr -d '"\r' || true
}
LEAD_CFG="${SITE_DIR}/wp-content/mu-plugins/sfrfr-lead.config.php"
SMART_CK="$(env_get SMARTCAPTCHA_CLIENT_KEY)"
GOOGLE_SK="$(env_get RECAPTCHA_SITE_KEY)"
LEAD_URL="$(env_get SFRFR_PUBLIC_LEAD_URL)"
LEAD_TOK="$(env_get SFRFR_PUBLIC_LEAD_TOKEN)"
if [ -z "${LEAD_TOK}" ]; then
  LEAD_TOK="$(env_get PUBLIC_LEAD_TOKEN)"
fi
if [ -z "${LEAD_URL}" ]; then
  LEAD_URL="https://api.proverkastaza.ru/api/public/leads"
fi
SMART_CK="$SMART_CK" GOOGLE_SK="$GOOGLE_SK" LEAD_URL="$LEAD_URL" LEAD_TOK="$LEAD_TOK" LEAD_CFG="$LEAD_CFG" \
  php -r '
$smart = getenv("SMART_CK") ?: "";
$google = getenv("GOOGLE_SK") ?: "";
$url = getenv("LEAD_URL") ?: "";
$tok = getenv("LEAD_TOK") ?: "";
$cfg = getenv("LEAD_CFG") ?: "";
$out = "<?php\n/** Generated by wp_apply_landing_vps.sh — без server-key SmartCaptcha */\nreturn [\n"
  . "    \"SMARTCAPTCHA_CLIENT_KEY\" => " . var_export($smart, true) . ",\n"
  . "    \"RECAPTCHA_SITE_KEY\" => " . var_export($google, true) . ",\n"
  . "    \"SFRFR_PUBLIC_LEAD_URL\" => " . var_export($url, true) . ",\n"
  . "    \"SFRFR_PUBLIC_LEAD_TOKEN\" => " . var_export($tok, true) . ",\n"
  . "    \"PUBLIC_LEAD_TOKEN\" => " . var_export($tok, true) . ",\n"
  . "];\n";
if ($cfg === "") { fwrite(STDERR, "LEAD_CFG empty\n"); exit(1); }
file_put_contents($cfg, $out);
'
chown www-data:www-data "$LEAD_CFG" 2>/dev/null || true
chmod 640 "$LEAD_CFG" 2>/dev/null || true
echo "MU site-footer + lead OK (clientKey len=${#SMART_CK})"
"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_ensure_lead_form.php" || true
echo
"${WP[@]}" eval-file "${APP_DIR}/scripts/wp_seed_blog_tz11.php"
echo

# Меню под короткую воронку (оферта/ПДн — в footer)
MENU_ID="$("${WP[@]}" menu list --format=json 2>/dev/null | php -r '
$j=json_decode(stream_get_contents(STDIN), true);
foreach ((array)$j as $m) { if (($m["name"] ?? "") === "SFRFR Primary") { echo (int)$m["term_id"]; exit; } }
' || true)"
if [ -n "${MENU_ID}" ]; then
  ITEMS="$("${WP[@]}" menu item list "$MENU_ID" --format=ids 2>/dev/null || true)"
  for iid in $ITEMS; do
    "${WP[@]}" menu item delete "$iid" >/dev/null 2>&1 || true
  done
  HOME_ID="$("${WP[@]}" option get page_on_front)"
  # Разделы главной — в выпадающем «Главная»; отдельные страницы — на верхнем уровне
  HOME_MENU_ID="$("${WP[@]}" menu item add-post "$MENU_ID" "$HOME_ID" --title="Главная" --porcelain | tr -d '[:space:]')"
  "${WP[@]}" menu item add-custom "$MENU_ID" "Как пользоваться MAX" "/#kak-rabotat" --parent-id="$HOME_MENU_ID" >/dev/null
  "${WP[@]}" menu item add-custom "$MENU_ID" "Кому полезна" "/#komu" --parent-id="$HOME_MENU_ID" >/dev/null
  "${WP[@]}" menu item add-custom "$MENU_ID" "Как это работает" "/#kak-prohodit" --parent-id="$HOME_MENU_ID" >/dev/null
  "${WP[@]}" menu item add-custom "$MENU_ID" "Тарифы" "/#tarify" --parent-id="$HOME_MENU_ID" >/dev/null
  "${WP[@]}" menu item add-custom "$MENU_ID" "Вопросы" "/#faq" --parent-id="$HOME_MENU_ID" >/dev/null
  "${WP[@]}" menu item add-custom "$MENU_ID" "Статьи" "/blog/" >/dev/null
  "${WP[@]}" menu item add-custom "$MENU_ID" "Эксперты" "/expert/" >/dev/null
  CABINET_URL="${CABINET_URL:-https://cabinet.proverkastaza.ru}"
  "${WP[@]}" menu item add-custom "$MENU_ID" "Личный кабинет" "${CABINET_URL%/}/" >/dev/null
  echo "MENU primary updated id=${MENU_ID} home_parent=${HOME_MENU_ID}"
fi

echo DONE
