#!/usr/bin/env bash
# Деплой MU-плагинов Яндекс Метрики / SEO robots / verification на WP.
# Публичный config Метрики (только COUNTER_ID) — www-data не читает /opt/sfrfr/.env
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SITE_DIR="${SITE_DIR:-/var/www/taxi-doroga-dobra}"
MU="${SITE_DIR}/wp-content/mu-plugins"
ENVF="${ENVF:-/opt/sfrfr/.env}"
SRC="${ROOT}/scripts/wp-mu-plugins"

mkdir -p "$MU"
for f in sfrfr-yandex-metrika.php sfrfr-seo-robots.php sfrfr-yandex-verification.php; do
  if [[ -f "$SRC/$f" ]]; then
    cp -f "$SRC/$f" "$MU/$f"
  fi
done

cid=""
webvisor="0"
if [[ -f "$ENVF" ]]; then
  cid="$(grep -E '^YANDEX_METRIKA_COUNTER_ID=' "$ENVF" | head -n1 | cut -d= -f2- | tr -d '\"' | tr -d "'" || true)"
  webvisor="$(grep -E '^YANDEX_METRIKA_WEBVISOR=' "$ENVF" | head -n1 | cut -d= -f2- | tr -d '\"' | tr -d "'" || true)"
  webvisor="${webvisor:-0}"
fi
cid="$(echo -n "$cid" | tr -cd '0-9')"

cfg="${MU}/sfrfr-yandex-metrika.config.php"
cat >"$cfg" <<EOF
<?php
/** Публичный конфиг Метрики (без OAuth). Generated by wp_deploy_metrika.sh */
return [
    'YANDEX_METRIKA_COUNTER_ID' => '${cid}',
    'YANDEX_METRIKA_WEBVISOR' => '${webvisor}',
];
EOF

chown www-data:www-data "$MU"/sfrfr-yandex-metrika.php "$MU"/sfrfr-seo-robots.php "$MU"/sfrfr-yandex-verification.php "$cfg" 2>/dev/null || true
chmod 644 "$MU"/sfrfr-yandex-metrika.php "$MU"/sfrfr-seo-robots.php "$MU"/sfrfr-yandex-verification.php "$cfg" 2>/dev/null || true

if [[ -z "$cid" ]]; then
  echo "WARN: YANDEX_METRIKA_COUNTER_ID пуст — плагин на сайте, счётчик не рисуется."
else
  echo "OK: yandex MU deployed; counter_id=$cid webvisor=$webvisor (+robots Clean-param, verification)"
fi
